### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by sagarladla** [StevenJokes/D2L_enread#1]
In file **2-5.ipynb**, **Output [7]** :

Can you explain me how did you calculated x' = 1? Some how I could not understood on D2L's guide also.

It would be big help.
Merci.

**Comment by StevenJokes** [comment]
x' = 1 is not precise.
x[x1, x2, x3, x4] = [0., 1., 2., 3.]
y = x.sum() is equal to y = x1+x2+x3+x4 
Then partial derivative: 
p(y)/p(x1) = p(y)/p(x2) = p(y)/p(x3) =p(y)/p(x4) = 1 （The coefficients of the linear equation)
My English is bad. Please let me know if it helps you.

**Comment by sagarladla** [comment]
Thanks mate, got it. 👍
